config/routes.rb
DisplayArt::Application.routes.draw do

  break if ARGV.join.include? 'assets:precompile'
  
  devise_for :users

  resources :arts
  
  root :to => "arts#index", :series => "Boxes"
  
  get '/series/:series' => 'arts#index'
  get '/arts/series/:series' => 'arts#index'  
  get '/series/:series/:id' => 'arts#show'
  get 'name/:name' => 'arts#show'
  

end

app/models/art.rb
class Art < ActiveRecord::Base
 
 validates_presence_of :name, :thumb, :image, :series, :sort_order
 validates_numericality_of :sort_order
 attr_protected

  def find_series_count(series_name)
    Art.find_by_sql("SELECT * FROM arts WHERE series = '#{series_name}'").count
  end
  
  def self.find_all_series()
#    Art.select('distinct(arts.series)')
#    Art.select('distinct(arts.series)').map{|a| a.series }
    Art.select('distinct series').order('series ASC').map{|a| a.series }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController

#before_filter :authorize, :only => [:new, :edit]
#before_filter :authenticate_user, :only => [:new, :edit]
 
  # GET /arts
  # GET /arts.json
  def index
    @arts = Art
    if params[:series] 
      @arts = @arts.where(:series => params[:series]).order("sort_order")
    end
    
    @arts = @arts.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arts }
    end
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
   
    if params[:name] 
      @art = Art.find_by_name(params[:name])
    else
      puts params[:id]
      @art = Art.find(Integer(params[:id]))
      puts @art
    end
    params[:series] = @art.series
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/new
  # GET /arts/new.json
  def new

    @art = Art.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/1/edit
  def edit
    @art = Art.find(params[:id])
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(params[:art])

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render json: @art, status: :created, location: @art }
      else
        format.html { render action: "new" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arts/1
  # PUT /arts/1.json
  def update
    @art = Art.find(params[:id])
    
    respond_to do |format|
      if @art.update_attributes(params[:art])
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art = Art.find(params[:id])
    ser = '/series/' + @art.series  
    @art.destroy

    respond_to do |format|
#      format.html { redirect_to arts_url }
      format.html { redirect_to ser }      
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper

  def draw_grid(size, cols, i)
    
      rows = size/cols 
			f = [0, cols-1]
			l = [size-cols, size-1]
			
			case i
			when (f[0]..f[1])
			   rend = "top"
			when (l[0]..l[1])
			   rend = "bottom"
			else
			   rend = "middle"
			end		
		
			if i % cols == 0					
				rend << "left"						
			elsif i % cols == cols -1 
				rend << "right"
			else 
				rend << "middle"
			end	
    end

end

app/views/arts/_bottomleft.html.erb
<div class="gridElement grBE" style="padding-bottom: 0pt; padding-left: 0pt;">

app/views/arts/_bottommiddle.html.erb
<div class="gridElement grBE" style="padding-bottom: 0pt;">

app/views/arts/_bottomright.html.erb
<div class="gridElement grBE grRE">

app/views/arts/_clear.html.erb
<div class="clr"></div>

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br />
    <%= f.text_field :thumb %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :sold %><br />
    <%= f.check_box :sold %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :prints_available %><br />
    <%= f.check_box :prints_available %>
  </div>
  <div class="field">
    <%= f.label :meta_data %><br />
    <%= f.text_field :meta_data %>
  </div>
  <div class="field">
    <%= f.label :series %><br />
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.text_field :sort_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/_menu.html.erb
<ul id="menu">	
<% Art.find_all_series.each do |a| %>
	<li class="<%='active' if params[:series] == a %>">
	<%= 
	if (request.url.to_s.include? 'series/') 
		link_to a, a
	else 
		link_to a, "series/" + a
	end
	%>	
	</li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to 'Add New Image', new_art_path %>
  </li>
<% end %>
</ul>

app/views/arts/_middleleft.html.erb
<div class="gridElement" style="padding-left: 0pt;">

app/views/arts/_middlemiddle.html.erb
<div class="gridElement">

app/views/arts/_topleft.html.erb
<div class="gridElement" style="margin-top: 28px; padding-top: 0px; padding-left: 0pt;">

app/views/arts/_topright.html.erb
<div class="gridElement grRE" style="margin-top: 28px; padding-top: 0px; padding-right: 0pt;">

app/views/arts/edit.html.erb
<h1 id="heading">Edit art</h1>

<div style="margin-left:15px">
<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', '/series/' + @art.series %>
</div>

app/views/arts/index.html.erb
<div id="big">

	<div id="menuWrap">
		<div id="session" style="margin-left:5px;">
		<% if user_signed_in? %>
		    <%= current_user.email %> is logged in. <br><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
		<% else %>
		    <%= link_to "Sign In to edit or add Artwork", new_user_session_path %>
		<% end %>
		</div>
		<%= render 'menu' %>		
	</div>
	<div id="content">
		<div id="mc">
				<% if @arts.size <= 9 
					cols = 3
				else
					cols = 4
				end %>	
			
				<% @arts.each_with_index do |art,i| %>
						
					<% if i % cols == 0 %>
						<div class="clr"></div>
					<% end %>	
										
					<% rend = draw_grid(@arts.size, cols, i) %>						

					<%= render rend %>
					<% if art.thumb == "plain.jpg" %>
						<%= image_tag(art.thumb) %>
					<% else %>
						<%= link_to image_tag(art.thumb), art %>
					<% end %>	
					</div>
				<% end %>
		</div>
		<div id="footer">
		</div>		
	</div>

app/views/arts/new.html.erb
<h1 id="heading">New art</h1>

<div style="margin-left:15px">
<%= render 'form' %>

<%= link_to 'Back', '/series/Boxes' %>
</div>

app/views/arts/show.html.erb
<div id="big">

	<div id="menuWrap">
		<div id="session" style="margin-left:5px;">
		<% if user_signed_in? %>
		    <%= current_user.email %> is logged in. <br><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
		<% else %>
		    <%= link_to "Sign In to edit or add Artwork", new_user_session_path %>
		<% end %>
		</div>
		<%= render 'menu' %>			
	</div>
	<div id="content">
		<div id="mc">
			<div style="margin-left:15px">
			<p id="notice"><%= notice %></p>

			<p>
			  	<br><br>
				<%= link_to image_tag(@art.image), '/series/' + @art.series %>
			</p>

			<table border="0" cellspacing="0" cellpadding="0" width="610px">
				<tr><td class="b"><br><br><%= @art.name %></td>
				</tr>
			</table>
			
			<% if user_signed_in? %>
				<p>
					<%= link_to 'Destroy', @art, confirm: 'Are you sure?', method: :delete %> |
					<%= link_to 'Edit', edit_art_path(@art) %> |
					<%= link_to 'Back', '/series/' + @art.series %>
				</p>
			<% end %>		
			</div>
		</div>
		<div id="footer">		
		</div>	
		</div>			
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DisplayArt</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!--
	<p style="margin-left:20px;" class="notice"> #notice </p>
	-->
	<p style="margin-left:20px;" class="alert"><%= alert %></p>
	<%= yield %>


</body>
</html>